[
  {
    name: 'Margherita Pizza',
    imageSrc: 'margherita_pizza.jpg',
    recipeAuthor: 'Giuseppe Conti',
    timeToCook: {
      Cook: '15 minutes',
      Prep: '2 hours',
    },
    difficulty: 'Easy',
    labels: ['Italian', 'Pizza', 'Dinner'],
    portions: '2',
    description:
      'Classic Margherita pizza with fresh tomatoes, mozzarella, and basil leaves.',
    nutrition: {
      kcal: '800',
      sugars: '5g',
      salt: '1.8g',
      carbs: '120g',
      protein: '30g',
      fat: '20g',
      saturates: '10g',
      fibre: '6g',
    },
    ingredients: [
      {
        item: 'Pizza Dough',
        measurement: 'g',
        quantity: 300,
      },
      {
        item: 'Tomato Sauce',
        measurement: 'g',
        quantity: 150,
      },
      {
        item: 'Fresh Mozzarella',
        measurement: 'g',
        quantity: 200,
      },
      {
        item: 'Fresh Tomatoes',
        measurement: 'medium',
        quantity: 2,
      },
      {
        item: 'Fresh Basil Leaves',
        measurement: 'leaves',
        quantity: 10,
      },
      {
        item: 'Olive Oil',
        measurement: 'tbsp',
        quantity: 2,
      },
      {
        item: 'Salt',
        measurement: 'tsp',
        quantity: 1,
      },
      {
        item: 'Black Pepper',
        measurement: 'tsp',
        quantity: 0.5,
      },
    ],
    steps: [
      'Preheat the oven to 220°C (425°F).',
      'Roll out the pizza dough into a round shape.',
      'Spread the tomato sauce evenly on the dough, leaving a border for the crust.',
      'Slice the fresh mozzarella and place it on top of the sauce.',
      'Slice the fresh tomatoes and arrange them on the pizza.',
      'Sprinkle with fresh basil leaves, salt, and black pepper.',
      'Drizzle olive oil over the pizza.',
      'Bake in the preheated oven for 12-15 minutes, or until the crust is golden and the cheese is melted and bubbly.',
      'Remove from the oven, let it cool for a few minutes, and serve.',
    ],
    vegan: false,
    vegetarian: true,
    cuisine: 'Italian',
    creatorAuth0Sub: '123456789',
  },
  {
    name: 'Chicken Parmesan',
    imageSrc: 'chicken_parmesan.jpg',
    recipeAuthor: 'Maria Rossi',
    timeToCook: {
      Cook: '30 minutes',
      Prep: '15 minutes',
    },
    difficulty: 'Medium',
    labels: ['Italian', 'Chicken', 'Dinner'],
    portions: '2',
    description:
      'Classic chicken Parmesan with breaded chicken, marinara sauce, and melted cheese.',
    nutrition: {
      kcal: '600',
      sugars: '6g',
      salt: '2g',
      carbs: '40g',
      protein: '40g',
      fat: '30g',
      saturates: '10g',
      fibre: '4g',
    },
    ingredients: [
      {
        item: 'Chicken Breasts',
        measurement: 'g',
        quantity: 400,
      },
      {
        item: 'Breadcrumbs',
        measurement: 'g',
        quantity: 100,
      },
      {
        item: 'Parmesan Cheese',
        measurement: 'g',
        quantity: 50,
      },
      {
        item: 'Egg',
        measurement: '',
        quantity: 1,
      },
      {
        item: 'All-Purpose Flour',
        measurement: 'g',
        quantity: 50,
      },
      {
        item: 'Olive Oil',
        measurement: 'tbsp',
        quantity: 2,
      },
      {
        item: 'Marinara Sauce',
        measurement: 'g',
        quantity: 200,
      },
      {
        item: 'Mozzarella Cheese',
        measurement: 'g',
        quantity: 150,
      },
      {
        item: 'Salt',
        measurement: 'tsp',
        quantity: 1,
      },
      {
        item: 'Black Pepper',
        measurement: 'tsp',
        quantity: 0.5,
      },
      {
        item: 'Fresh Basil Leaves',
        measurement: 'leaves',
        quantity: 6,
      },
    ],
    steps: [
      'Preheat the oven to 200°C (400°F).',
      'Season the chicken breasts with salt and black pepper.',
      'In a shallow bowl, combine the breadcrumbs and grated Parmesan cheese.',
      'In another bowl, beat the egg.',
      'Dredge the chicken breasts in flour, then dip them in the beaten egg, and coat them with the breadcrumb mixture.',
      'Heat olive oil in a large skillet over medium heat. Cook the breaded chicken breasts until golden brown on both sides.',
      'Transfer the chicken breasts to a baking dish. Spoon marinara sauce over each breast, then top with mozzarella cheese.',
      'Bake in the preheated oven for 15-20 minutes, or until the chicken is cooked through and the cheese is melted and bubbly.',
      'Garnish with fresh basil leaves and serve.',
    ],
    vegan: false,
    vegetarian: false,
    cuisine: 'Italian',
    creatorAuth0Sub: '987654321',
  },
  {
    name: 'Beef Tacos',
    imageSrc: 'beef_tacos.jpg',
    recipeAuthor: 'Carlos Hernandez',
    timeToCook: {
      Cook: '20 minutes',
      Prep: '10 minutes',
    },
    difficulty: 'Easy',
    labels: ['Mexican', 'Beef', 'Dinner'],
    portions: '4',
    description:
      'Delicious beef tacos with seasoned ground beef, salsa, and toppings.',
    nutrition: {
      kcal: '450',
      sugars: '3g',
      salt: '1.2g',
      carbs: '30g',
      protein: '25g',
      fat: '25g',
      saturates: '10g',
      fibre: '6g',
    },
    ingredients: [
      {
        item: 'Ground Beef',
        measurement: 'g',
        quantity: 500,
      },
      {
        item: 'Taco Shells',
        measurement: 'units',
        quantity: 8,
      },
      {
        item: 'Onion',
        measurement: 'medium',
        quantity: 1,
      },
      {
        item: 'Garlic',
        measurement: 'clove',
        quantity: 3,
      },
      {
        item: 'Tomato',
        measurement: 'medium',
        quantity: 1,
      },
      {
        item: 'Lettuce',
        measurement: 'leaves',
        quantity: 4,
      },
      {
        item: 'Cheddar Cheese',
        measurement: 'g',
        quantity: 100,
      },
      {
        item: 'Sour Cream',
        measurement: 'g',
        quantity: 100,
      },
      {
        item: 'Salsa',
        measurement: 'g',
        quantity: 100,
      },
      {
        item: 'Cumin',
        measurement: 'tsp',
        quantity: 1,
      },
      {
        item: 'Chili Powder',
        measurement: 'tsp',
        quantity: 1,
      },
      {
        item: 'Paprika',
        measurement: 'tsp',
        quantity: 1,
      },
      {
        item: 'Salt',
        measurement: 'tsp',
        quantity: 1,
      },
      {
        item: 'Black Pepper',
        measurement: 'tsp',
        quantity: 0.5,
      },
    ],
    steps: [
      'Heat a skillet over medium-high heat. Add the ground beef and cook until browned.',
      'Add chopped onion and minced garlic to the skillet. Cook until the onion is translucent.',
      'Stir in diced tomatoes, cumin, chili powder, paprika, salt, and black pepper. Cook for a few more minutes.',
      'Heat the taco shells according to the package instructions.',
      'Fill each taco shell with the beef mixture.',
      'Top with shredded lettuce, grated cheddar cheese, sour cream, and salsa.',
      'Serve the beef tacos immediately.',
    ],
    vegan: false,
    vegetarian: false,
    cuisine: 'Mexican',
    creatorAuth0Sub: '135792468',
  },
  {
    name: 'Caprese Salad',
    imageSrc: 'caprese_salad.jpg',
    recipeAuthor: 'Francesca Romano',
    timeToCook: {
      Cook: '0 minutes',
      Prep: '10 minutes',
    },
    difficulty: 'Easy',
    labels: ['Italian', 'Salad', 'Appetizer'],
    portions: '2',
    description:
      'Simple and refreshing Caprese salad with tomatoes, mozzarella, and basil.',
    nutrition: {
      kcal: '250',
      sugars: '4g',
      salt: '0.8g',
      carbs: '8g',
      protein: '15g',
      fat: '18g',
      saturates: '8g',
      fibre: '2g',
    },
    ingredients: [
      {
        item: 'Ripe Tomatoes',
        measurement: 'medium',
        quantity: 2,
      },
      {
        item: 'Fresh Mozzarella',
        measurement: 'g',
        quantity: 200,
      },
      {
        item: 'Fresh Basil Leaves',
        measurement: 'leaves',
        quantity: 10,
      },
      {
        item: 'Extra Virgin Olive Oil',
        measurement: 'tbsp',
        quantity: 2,
      },
      {
        item: 'Balsamic Vinegar',
        measurement: 'tbsp',
        quantity: 1,
      },
      {
        item: 'Salt',
        measurement: 'tsp',
        quantity: 0.5,
      },
      {
        item: 'Black Pepper',
        measurement: 'tsp',
        quantity: 0.5,
      },
    ],
    steps: [
      'Slice the tomatoes and fresh mozzarella into thick slices.',
      'Arrange the tomato and mozzarella slices on a serving plate, alternating them.',
      'Tuck fresh basil leaves between the tomato and mozzarella slices.',
      'Drizzle extra virgin olive oil and balsamic vinegar over the salad.',
      'Season with salt and black pepper.',
      'Let the salad sit for a few minutes to allow the flavors to meld together.',
      'Serve the Caprese salad as a refreshing appetizer or side dish.',
    ],
    vegan: false,
    vegetarian: true,
    cuisine: 'Italian',
    creatorAuth0Sub: '246813579',
  },
  {
    name: 'Mushroom Risotto',
    imageSrc: 'mushroom_risotto.jpg',
    recipeAuthor: 'Antonio Rossi',
    timeToCook: {
      Cook: '30 minutes',
      Prep: '10 minutes',
    },
    difficulty: 'Medium',
    labels: ['Italian', 'Risotto', 'Dinner'],
    portions: '4',
    description:
      'Creamy mushroom risotto cooked with Arborio rice and Parmesan cheese.',
    nutrition: {
      kcal: '500',
      sugars: '3g',
      salt: '1.2g',
      carbs: '70g',
      protein: '10g',
      fat: '20g',
      saturates: '8g',
      fibre: '3g',
    },
    ingredients: [
      {
        item: 'Arborio Rice',
        measurement: 'g',
        quantity: 300,
      },
      {
        item: 'Mushrooms',
        measurement: 'g',
        quantity: 200,
      },
      {
        item: 'Onion',
        measurement: 'medium',
        quantity: 1,
      },
      {
        item: 'Garlic',
        measurement: 'clove',
        quantity: 2,
      },
      {
        item: 'Vegetable Broth',
        measurement: 'ml',
        quantity: 1000,
      },
      {
        item: 'White Wine',
        measurement: 'ml',
        quantity: 150,
      },
      {
        item: 'Parmesan Cheese',
        measurement: 'g',
        quantity: 50,
      },
      {
        item: 'Butter',
        measurement: 'tbsp',
        quantity: 2,
      },
      {
        item: 'Olive Oil',
        measurement: 'tbsp',
        quantity: 2,
      },
      {
        item: 'Salt',
        measurement: 'tsp',
        quantity: 1,
      },
      {
        item: 'Black Pepper',
        measurement: 'tsp',
        quantity: 0.5,
      },
    ],
    steps: [
      'In a large saucepan, heat olive oil and butter over medium heat.',
      'Add chopped onion and minced garlic to the saucepan. Cook until the onion is translucent.',
      'Add sliced mushrooms to the saucepan. Cook until the mushrooms are browned and tender.',
      'Stir in Arborio rice and cook for 2-3 minutes until lightly toasted.',
      'Pour in white wine and cook until the liquid is absorbed.',
      'Gradually add vegetable broth, about 1 cup at a time, stirring constantly and allowing each addition to be absorbed before adding more.',
      'Continue cooking and stirring until the rice is al dente and creamy.',
      'Stir in grated Parmesan cheese. Season with salt and black pepper.',
      'Remove from heat and let the risotto rest for a few minutes before serving.',
    ],
    vegan: false,
    vegetarian: true,
    cuisine: 'Italian',
    creatorAuth0Sub: '951357456',
  },
  {
    name: 'Pasta Carbonara',
    imageSrc: 'pasta_carbonara.jpg',
    recipeAuthor: 'Marco Bianchi',
    timeToCook: {
      Cook: '15 minutes',
      Prep: '5 minutes',
    },
    difficulty: 'Easy',
    labels: ['Italian', 'Pasta', 'Dinner'],
    portions: '2',
    description:
      'Classic Pasta Carbonara with bacon, eggs, Parmesan cheese, and black pepper.',
    nutrition: {
      kcal: '600',
      sugars: '3g',
      salt: '1.5g',
      carbs: '60g',
      protein: '30g',
      fat: '25g',
      saturates: '10g',
      fibre: '2g',
    },
    ingredients: [
      {
        item: 'Spaghetti',
        measurement: 'g',
        quantity: 200,
      },
      {
        item: 'Bacon',
        measurement: 'g',
        quantity: 100,
      },
      {
        item: 'Eggs',
        measurement: '',
        quantity: 2,
      },
      {
        item: 'Parmesan Cheese',
        measurement: 'g',
        quantity: 50,
      },
      {
        item: 'Salt',
        measurement: 'tsp',
        quantity: 0.5,
      },
      {
        item: 'Black Pepper',
        measurement: 'tsp',
        quantity: 0.5,
      },
    ],
    steps: [
      'Cook the spaghetti according to the package instructions.',
      'Meanwhile, cook the bacon in a skillet until crispy. Remove from the skillet and chop into small pieces.',
      'In a bowl, whisk together eggs, grated Parmesan cheese, salt, and black pepper.',
      'Drain the cooked spaghetti and return it to the pot. Immediately add the egg mixture and chopped bacon to the hot spaghetti. Toss well to coat the pasta evenly and allow the heat to cook the eggs and create a creamy sauce.',
      'Serve the Pasta Carbonara immediately, garnished with additional grated Parmesan cheese and black pepper.',
    ],
    vegan: false,
    vegetarian: false,
    cuisine: 'Italian',
    creatorAuth0Sub: '753951852',
  },
  {
    name: 'Thai Green Curry',
    imageSrc: 'thai_green_curry.jpg',
    recipeAuthor: 'Nongpanga Phengphian',
    timeToCook: {
      Cook: '20 minutes',
      Prep: '10 minutes',
    },
    difficulty: 'Medium',
    labels: ['Thai', 'Curry', 'Dinner'],
    portions: '2',
    description:
      'Flavorful Thai green curry with chicken, vegetables, and coconut milk.',
    nutrition: {
      kcal: '500',
      sugars: '5g',
      salt: '1.2g',
      carbs: '30g',
      protein: '25g',
      fat: '35g',
      saturates: '20g',
      fibre: '4g',
    },
    ingredients: [
      {
        item: 'Chicken Breast',
        measurement: 'g',
        quantity: 300,
      },
      {
        item: 'Thai Green Curry Paste',
        measurement: 'g',
        quantity: 50,
      },
      {
        item: 'Coconut Milk',
        measurement: 'ml',
        quantity: 400,
      },
      {
        item: 'Eggplant',
        measurement: 'g',
        quantity: 200,
      },
      {
        item: 'Bell Pepper',
        measurement: 'medium',
        quantity: 1,
      },
      {
        item: 'Green Beans',
        measurement: 'g',
        quantity: 100,
      },
      {
        item: 'Basil Leaves',
        measurement: 'leaves',
        quantity: 10,
      },
      {
        item: 'Fish Sauce',
        measurement: 'tbsp',
        quantity: 2,
      },
      {
        item: 'Sugar',
        measurement: 'tbsp',
        quantity: 1,
      },
      {
        item: 'Salt',
        measurement: 'tsp',
        quantity: 0.5,
      },
    ],
    steps: [
      'Heat a small amount of coconut milk in a pan over medium heat. Add the Thai green curry paste and cook for a few minutes until fragrant.',
      'Add sliced chicken breast to the pan. Cook until the chicken is cooked through.',
      'Add coconut milk, chopped eggplant, sliced bell pepper, and green beans to the pan. Simmer until the vegetables are tender.',
      'Stir in fish sauce, sugar, and salt. Taste and adjust the seasoning if needed.',
      'Add fresh basil leaves to the pan and stir briefly to wilt the basil.',
      'Serve the Thai Green Curry over steamed rice.',
    ],
    vegan: false,
    vegetarian: false,
    cuisine: 'Thai',
    creatorAuth0Sub: '159357456',
  },
  {
    name: 'Caesar Salad',
    imageSrc: 'caesar_salad.jpg',
    recipeAuthor: 'Sophia Johnson',
    timeToCook: {
      Cook: '0 minutes',
      Prep: '15 minutes',
    },
    difficulty: 'Easy',
    labels: ['Salad', 'Appetizer'],
    portions: '2',
    description:
      'Classic Caesar salad with crisp romaine lettuce, Parmesan cheese, and homemade dressing.',
    nutrition: {
      kcal: '350',
      sugars: '3g',
      salt: '1.2g',
      carbs: '15g',
      protein: '10g',
      fat: '30g',
      saturates: '5g',
      fibre: '4g',
    },
    ingredients: [
      {
        item: 'Romaine Lettuce',
        measurement: 'g',
        quantity: 200,
      },
      {
        item: 'Croutons',
        measurement: 'g',
        quantity: 50,
      },
      {
        item: 'Parmesan Cheese',
        measurement: 'g',
        quantity: 50,
      },
      {
        item: 'Anchovy Fillets',
        measurement: 'units',
        quantity: 2,
      },
      {
        item: 'Garlic',
        measurement: 'clove',
        quantity: 1,
      },
      {
        item: 'Lemon Juice',
        measurement: 'tbsp',
        quantity: 1,
      },
      {
        item: 'Dijon Mustard',
        measurement: 'tsp',
        quantity: 1,
      },
      {
        item: 'Worcestershire Sauce',
        measurement: 'tsp',
        quantity: 1,
      },
      {
        item: 'Olive Oil',
        measurement: 'tbsp',
        quantity: 2,
      },
      {
        item: 'Salt',
        measurement: 'tsp',
        quantity: 0.5,
      },
      {
        item: 'Black Pepper',
        measurement: 'tsp',
        quantity: 0.5,
      },
    ],
    steps: [
      'Tear the romaine lettuce into bite-sized pieces and place them in a large salad bowl.',
      'In a blender or food processor, combine anchovy fillets, minced garlic, lemon juice, Dijon mustard, Worcestershire sauce, olive oil, salt, and black pepper. Blend until smooth.',
      'Drizzle the dressing over the romaine lettuce and toss to coat the leaves evenly.',
      'Sprinkle croutons and grated Parmesan cheese over the salad.',
      'Serve the Caesar salad immediately as an appetizer or side dish.',
    ],
    vegan: false,
    vegetarian: true,
    cuisine: 'International',
    creatorAuth0Sub: '753951852',
  },
  {
    name: 'Beef Stir-Fry',
    imageSrc: 'beef_stir_fry.jpg',
    recipeAuthor: 'David Chen',
    timeToCook: {
      Cook: '15 minutes',
      Prep: '10 minutes',
    },
    difficulty: 'Easy',
    labels: ['Asian', 'Stir-Fry', 'Dinner'],
    portions: '2',
    description:
      'Quick and flavorful beef stir-fry with vegetables and soy sauce.',
    nutrition: {
      kcal: '400',
      sugars: '5g',
      salt: '1.2g',
      carbs: '30g',
      protein: '30g',
      fat: '15g',
      saturates: '5g',
      fibre: '4g',
    },
    ingredients: [
      {
        item: 'Beef Sirloin',
        measurement: 'g',
        quantity: 300,
      },
      {
        item: 'Broccoli',
        measurement: 'g',
        quantity: 200,
      },
      {
        item: 'Bell Pepper',
        measurement: 'medium',
        quantity: 1,
      },
      {
        item: 'Carrot',
        measurement: 'medium',
        quantity: 1,
      },
      {
        item: 'Snow Peas',
        measurement: 'g',
        quantity: 100,
      },
      {
        item: 'Garlic',
        measurement: 'clove',
        quantity: 3,
      },
      {
        item: 'Ginger',
        measurement: 'tsp',
        quantity: 1,
      },
      {
        item: 'Soy Sauce',
        measurement: 'tbsp',
        quantity: 2,
      },
      {
        item: 'Sesame Oil',
        measurement: 'tbsp',
        quantity: 1,
      },
      {
        item: 'Cornstarch',
        measurement: 'tsp',
        quantity: 1,
      },
      {
        item: 'Salt',
        measurement: 'tsp',
        quantity: 0.5,
      },
      {
        item: 'Cooking Oil',
        measurement: 'tbsp',
        quantity: 2,
      },
      {
        item: 'Rice',
        measurement: 'g',
        quantity: 150,
      },
    ],
    steps: [
      'Cook the rice according to the package instructions.',
      'Slice the beef sirloin into thin strips.',
      'Heat the cooking oil in a large pan or wok. Add the beef and cook until browned.',
      'Add the sliced bell pepper, broccoli florets, carrot strips, snow peas, minced garlic, and grated ginger to the pan. Stir-fry for a few minutes.',
      'In a small bowl, whisk together soy sauce, sesame oil, cornstarch, and salt. Pour the sauce over the beef and vegetables. Stir-fry for another 2-3 minutes until the sauce thickens.',
      'Serve the beef stir-fry over the cooked rice.',
    ],
    vegan: false,
    vegetarian: false,
    cuisine: 'Asian',
    creatorAuth0Sub: '987654321',
  },

  {
    name: 'Spaghetti Bolognese',
    imageSrc: 'spaghetti_bolognese.jpg',
    recipeAuthor: 'Jamie Oliver',
    timeToCook: {
      Cook: '30 minutes',
      Prep: '15 minutes',
    },
    difficulty: 'Easy',
    labels: ['Italian', 'Pasta', 'Dinner'],
    portions: '4',
    description:
      'Classic spaghetti Bolognese recipe with a rich tomato sauce and minced beef.',
    nutrition: {
      kcal: '400',
      sugars: '7g',
      salt: '1.5g',
      carbs: '55g',
      protein: '20g',
      fat: '12g',
      saturates: '4g',
      fibre: '6g',
    },
    ingredients: [
      {
        item: 'Spaghetti',
        measurement: 'g',
        quantity: 300,
      },
      {
        item: 'Minced Beef',
        measurement: 'g',
        quantity: 500,
      },
      {
        item: 'Onion',
        measurement: 'medium',
        quantity: 1,
      },
      {
        item: 'Garlic',
        measurement: 'clove',
        quantity: 2,
      },
      {
        item: 'Carrot',
        measurement: 'medium',
        quantity: 1,
      },
      {
        item: 'Celery',
        measurement: 'stalk',
        quantity: 1,
      },
      {
        item: 'Tomato Paste',
        measurement: 'g',
        quantity: 30,
      },
      {
        item: 'Canned Chopped Tomatoes',
        measurement: 'g',
        quantity: 400,
      },
      {
        item: 'Beef Stock',
        measurement: 'ml',
        quantity: 200,
      },
      {
        item: 'Olive Oil',
        measurement: 'tbsp',
        quantity: 2,
      },
      {
        item: 'Salt',
        measurement: 'tsp',
        quantity: 1,
      },
      {
        item: 'Black Pepper',
        measurement: 'tsp',
        quantity: 0.5,
      },
      {
        item: 'Parmesan Cheese',
        measurement: 'g',
        quantity: 50,
      },
    ],
    steps: [
      'Cook the spaghetti according to the package instructions.',
      'Heat the olive oil in a large pan and add the minced beef. Cook until browned.',
      'Add the chopped onion, garlic, carrot, and celery to the pan. Cook until softened.',
      'Stir in the tomato paste and cook for 1 minute.',
      'Pour in the canned chopped tomatoes and beef stock. Season with salt and black pepper. Simmer for 20 minutes.',
      'Serve the Bolognese sauce over the cooked spaghetti and sprinkle with grated Parmesan cheese.',
    ],
    vegan: false,
    vegetarian: false,
    cuisine: 'Italian',
    creatorAuth0Sub: '123456789',
  },
  {
    name: 'Chicken Stir-Fry',
    imageSrc: 'chicken_stir_fry.jpg',
    recipeAuthor: 'Gordon Ramsay',
    timeToCook: {
      Cook: '15 minutes',
      Prep: '10 minutes',
    },
    difficulty: 'Medium',
    labels: ['Asian', 'Stir-Fry', 'Dinner'],
    portions: '2',
    description:
      'Quick and flavorful chicken stir-fry with vegetables and soy sauce.',
    nutrition: {
      kcal: '300',
      sugars: '5g',
      salt: '1.2g',
      carbs: '25g',
      protein: '30g',
      fat: '8g',
      saturates: '2g',
      fibre: '4g',
    },
    ingredients: [
      {
        item: 'Chicken Breast',
        measurement: 'g',
        quantity: 300,
      },
      {
        item: 'Bell Pepper',
        measurement: 'medium',
        quantity: 1,
      },
      {
        item: 'Broccoli',
        measurement: 'g',
        quantity: 200,
      },
      {
        item: 'Carrot',
        measurement: 'medium',
        quantity: 1,
      },
      {
        item: 'Snow Peas',
        measurement: 'g',
        quantity: 100,
      },
      {
        item: 'Garlic',
        measurement: 'clove',
        quantity: 3,
      },
      {
        item: 'Ginger',
        measurement: 'tsp',
        quantity: 1,
      },
      {
        item: 'Soy Sauce',
        measurement: 'tbsp',
        quantity: 2,
      },
      {
        item: 'Sesame Oil',
        measurement: 'tbsp',
        quantity: 1,
      },
      {
        item: 'Cornstarch',
        measurement: 'tsp',
        quantity: 1,
      },
      {
        item: 'Salt',
        measurement: 'tsp',
        quantity: 0.5,
      },
      {
        item: 'Cooking Oil',
        measurement: 'tbsp',
        quantity: 2,
      },
      {
        item: 'Rice',
        measurement: 'g',
        quantity: 150,
      },
    ],
    steps: [
      'Cook the rice according to the package instructions.',
      'Slice the chicken breast into thin strips.',
      'Heat the cooking oil in a large pan or wok. Add the chicken and cook until browned.',
      'Add the sliced bell pepper, broccoli florets, carrot strips, snow peas, minced garlic, and grated ginger to the pan. Stir-fry for a few minutes.',
      'In a small bowl, whisk together soy sauce, sesame oil, cornstarch, and salt. Pour the sauce over the chicken and vegetables. Stir-fry for another 2-3 minutes until the sauce thickens.',
      'Serve the chicken stir-fry over the cooked rice.',
    ],
    vegan: false,
    vegetarian: false,
    cuisine: 'Asian',
    creatorAuth0Sub: '987654321',
  },
];
