AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket with CORS and lifecycle rules
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - x-amz-*
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins: !Ref AllowedOrigins
            ExposedHeaders:
              - x-amz-server-side-encryption
              - x-amz-request-id
              - x-amz-id-2
            Id: myCORSRuleId1
            MaxAge: 3600
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            Prefix: images/
            Id: Delete images after 30 days
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
              NewerNoncurrentVersions: 3
      Tags:
        - Key: Name
          Value: !Ref BucketName
Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Description: Name of the sample Amazon S3 bucket with CORS enabled.
Parameters:
  BucketName:
    Description: Bucket Name for image upload
    Type: String
    Default: justcook-bucket-dev
  AllowedOrigins:
    Description: Allowed origins for CORS
    Type: CommaDelimitedList
    Default: https://localhost:3000,https://www.justcook.ing